server:
  port: 8081

dock:
  private-key-path: private_key.pem
  storage:
    path: data/envelopes

aws:
  region: us-east-1
  sns:
    topic-arn: ""
  sqs:
    dlq-url: ""

spring:
  datasource:
    url: jdbc:h2:mem:dockdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
